apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.fullname" . }}-env
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
    GIT_HOST={{ .Values.git.host }}
    GIT_USER=gitlab-ci-token
    GIT_TOKEN={{ .Values.git.token }}
    OLLAMA_HOST={{ .Values.config.ollama_host }}
    OLLAMA_MODEL={{ .Values.config.ollama_model }}
