apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orchestrator-pdb
  labels:
    app.kubernetes.io/name: hivemind
    app.kubernetes.io/component: orchestrator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hivemind
      app.kubernetes.io/component: orchestrator