# Copyright 2026 Mael Klingler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Database module – hybrid adapter pattern.

Selects the backend based on environment variables:
  - SUPABASE_URL + SUPABASE_SERVICE_KEY → Supabase (cloud or self-hosted)
  - DATABASE_URL=postgresql://... → PostgreSQL (raw psycopg2)
  - Default → SQLite (local dev)

Usage:
  from database import create_ticket, get_tickets, ...
  
All functions delegate to the appropriate backend automatically.
"""

import os

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")
USE_SUPABASE = bool(SUPABASE_URL and SUPABASE_SERVICE_KEY)

if USE_SUPABASE:
    from database.supabase_adapter import (
        init_db,
        ensure_config_defaults,
        import_settings_from_env,
        create_ticket,
        get_tickets,
        get_ticket,
        update_ticket_status,
        stop_ticket,
        get_tickets_with_queue,
        update_ticket_review,
        set_ticket_mr_url,
        set_ticket_workspace,
        set_ticket_ai_planning,
        update_ticket_description,
        requeue_ticket,
        reopen_ticket,
        get_failed_tickets,
        get_open_mr_tickets,
        update_ticket_mr_tracking,
        get_agent,
        get_or_create_agent,
        set_agent_status,
        get_all_agents,
        get_idle_agents,
        get_max_agents,
        set_max_agents,
        ensure_agent_pool,
        create_agent,
        update_agent_profile,
        delete_agent,
        set_agent_skills,
        set_agent_instruction_assignments,
        get_agent_with_profile,
        get_all_agents_with_profiles,
        get_agent_mcp_servers,
        get_agent_assigned_instructions,
        get_next_queue_item,
        assign_queue_item,
        complete_queue_item,
        fail_queue_item,
        get_queue,
        add_step,
        get_steps,
        get_all_steps,
        get_all_settings,
        get_setting,
        set_setting,
        get_mcp_servers,
        get_enabled_mcp_servers,
        add_mcp_server,
        update_mcp_server,
        delete_mcp_server,
        get_agent_instructions,
        get_enabled_agent_instructions,
        add_agent_instruction,
        update_agent_instruction,
        delete_agent_instruction,
        get_opencode_plugins,
        get_enabled_opencode_plugins,
        get_enabled_plugin_names,
        add_opencode_plugin,
        update_opencode_plugin,
        delete_opencode_plugin,
        get_agent_memory_blocks,
        set_agent_memory_block,
        get_agent_memory_as_markdown,
        delete_agent_memory_block,
        seed_default_memory_blocks,
        get_all_repos,
        get_repo,
        add_repo,
        delete_repo,
        update_repo,
        import_repos_from_config,
        set_repo_active,
        get_agent_repo_affinities,
        set_agent_repo_affinities,
        get_all_repo_names,
        find_best_agent_for_repo,
        add_ticket_comment,
        get_ticket_comments,
        create_ticket_group,
        get_ticket_group,
        add_team_message,
        get_team_messages,
        record_metric_event,
        get_metric_events,
        get_metrics_summary,
        update_ticket_phase_timestamp,
        update_ticket_llm_usage,
        increment_review_cycle_count,
        set_ticket_first_pipeline_status,
        set_ticket_completed_at,
        set_ticket_primary_repo,
        set_ticket_line_stats,
        get_db,
    )
else:
    from database.sqlite_adapter import (
        init_db,
        ensure_config_defaults,
        import_settings_from_env,
        create_ticket,
        get_tickets,
        get_ticket,
        update_ticket_status,
        stop_ticket,
        get_tickets_with_queue,
        update_ticket_review,
        set_ticket_mr_url,
        set_ticket_workspace,
        set_ticket_ai_planning,
        update_ticket_description,
        requeue_ticket,
        reopen_ticket,
        get_failed_tickets,
        get_open_mr_tickets,
        update_ticket_mr_tracking,
        get_agent,
        get_or_create_agent,
        set_agent_status,
        get_all_agents,
        get_idle_agents,
        get_max_agents,
        set_max_agents,
        ensure_agent_pool,
        create_agent,
        update_agent_profile,
        delete_agent,
        set_agent_skills,
        set_agent_instruction_assignments,
        get_agent_with_profile,
        get_all_agents_with_profiles,
        get_agent_mcp_servers,
        get_agent_assigned_instructions,
        get_next_queue_item,
        assign_queue_item,
        complete_queue_item,
        fail_queue_item,
        get_queue,
        add_step,
        get_steps,
        get_all_steps,
        get_all_settings,
        get_setting,
        set_setting,
        get_mcp_servers,
        get_enabled_mcp_servers,
        add_mcp_server,
        update_mcp_server,
        delete_mcp_server,
        get_agent_instructions,
        get_enabled_agent_instructions,
        add_agent_instruction,
        update_agent_instruction,
        delete_agent_instruction,
        get_opencode_plugins,
        get_enabled_opencode_plugins,
        get_enabled_plugin_names,
        add_opencode_plugin,
        update_opencode_plugin,
        delete_opencode_plugin,
        get_agent_memory_blocks,
        set_agent_memory_block,
        get_agent_memory_as_markdown,
        delete_agent_memory_block,
        seed_default_memory_blocks,
        get_all_repos,
        get_repo,
        add_repo,
        delete_repo,
        update_repo,
        import_repos_from_config,
        set_repo_active,
        get_agent_repo_affinities,
        set_agent_repo_affinities,
        get_all_repo_names,
        find_best_agent_for_repo,
        add_ticket_comment,
        get_ticket_comments,
        create_ticket_group,
        get_ticket_group,
        add_team_message,
        get_team_messages,
        record_metric_event,
        get_metric_events,
        get_metrics_summary,
        update_ticket_phase_timestamp,
        update_ticket_llm_usage,
        increment_review_cycle_count,
        set_ticket_first_pipeline_status,
        set_ticket_completed_at,
        set_ticket_primary_repo,
        set_ticket_line_stats,
        get_db,
    )

# Auto-init on import (for both backends)
try:
    init_db()
    if not USE_SUPABASE:
        ensure_config_defaults()
        import_settings_from_env()
except Exception:
    pass

__all__ = [
    "get_db", "init_db",
    "create_ticket", "get_tickets", "get_ticket", "update_ticket_status",
    "stop_ticket", "get_tickets_with_queue", "update_ticket_review",
    "set_ticket_mr_url", "set_ticket_workspace", "set_ticket_ai_planning",
    "update_ticket_description",
    "requeue_ticket", "reopen_ticket", "get_failed_tickets",
    "get_open_mr_tickets", "update_ticket_mr_tracking",
    "get_agent", "get_or_create_agent", "set_agent_status",
    "get_all_agents", "get_idle_agents", "get_max_agents", "set_max_agents",
    "ensure_agent_pool", "create_agent", "update_agent_profile",
    "delete_agent", "set_agent_skills", "set_agent_instruction_assignments",
    "get_agent_with_profile", "get_all_agents_with_profiles",
    "get_agent_mcp_servers", "get_agent_assigned_instructions",
    "get_next_queue_item", "assign_queue_item", "complete_queue_item",
    "fail_queue_item", "get_queue", "add_step", "get_steps", "get_all_steps",
    "ensure_config_defaults", "get_all_settings", "get_setting", "set_setting",
    "import_settings_from_env",
    "get_mcp_servers", "get_enabled_mcp_servers", "add_mcp_server",
    "update_mcp_server", "delete_mcp_server",
    "get_agent_instructions", "get_enabled_agent_instructions",
    "add_agent_instruction", "update_agent_instruction", "delete_agent_instruction",
    "get_opencode_plugins", "get_enabled_opencode_plugins",
    "get_enabled_plugin_names", "add_opencode_plugin",
    "update_opencode_plugin", "delete_opencode_plugin",
    "get_agent_memory_blocks", "set_agent_memory_block",
    "get_agent_memory_as_markdown", "delete_agent_memory_block",
    "seed_default_memory_blocks",
    "get_all_repos", "get_repo", "add_repo", "delete_repo", "update_repo",
    "import_repos_from_config", "set_repo_active",
    "add_ticket_comment", "get_ticket_comments",
    "create_ticket_group", "get_ticket_group",
    "add_team_message", "get_team_messages",
    "get_agent_repo_affinities", "set_agent_repo_affinities",
    "find_best_agent_for_repo", "get_all_repo_names",
    "record_metric_event", "get_metric_events", "get_metrics_summary",
    "update_ticket_phase_timestamp", "update_ticket_llm_usage",
    "increment_review_cycle_count", "set_ticket_first_pipeline_status",
    "set_ticket_completed_at", "set_ticket_primary_repo",
    "set_ticket_line_stats",
    "USE_SUPABASE",
]