# Copyright 2026 Mael Klingler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Database adapter protocol – defines the interface that all backends must implement.
Supports SQLite (local dev), PostgreSQL, and Supabase.
"""

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class DatabaseAdapter(Protocol):
    # ── Init ───────────────────────────────────────────
    def init_db(self) -> None: ...
    def ensure_config_defaults(self) -> None: ...
    def import_settings_from_env(self) -> None: ...

    # ── Tickets ───────────────────────────────────────
    def create_ticket(self, ticket: Dict[str, Any]) -> str: ...
    def get_tickets(self, status: Optional[str] = None) -> List[Dict]: ...
    def get_ticket(self, ticket_id: str) -> Optional[Dict]: ...
    def update_ticket_status(self, ticket_id: str, status: str) -> None: ...
    def stop_ticket(self, ticket_id: str) -> bool: ...
    def get_tickets_with_queue(self) -> List[Dict]: ...
    def update_ticket_review(self, ticket_id: str, review_status: str, notes: str = "", mr_url: str = "") -> None: ...
    def set_ticket_mr_url(self, ticket_id: str, mr_url: str) -> None: ...
    def set_ticket_workspace(self, ticket_id: str, workspace_path: str, agent_id: str) -> None: ...
    def set_ticket_ai_planning(self, ticket_id: str, planning: Dict) -> None: ...
    def requeue_ticket(self, ticket_id: str, max_retries: int = 3) -> bool: ...
    def reopen_ticket(self, ticket_id: str) -> bool: ...
    def get_failed_tickets(self) -> List[Dict]: ...
    def get_open_mr_tickets(self) -> List[Dict]: ...
    def update_ticket_mr_tracking(self, ticket_id: str, **kwargs) -> None: ...
    def update_ticket_description(self, ticket_id: str, description: str) -> None: ...

    # ── Agents ────────────────────────────────────────
    def get_agent(self, agent_id: str) -> Optional[Dict]: ...
    def get_or_create_agent(self, agent_id: str, name: str = "") -> Dict: ...
    def set_agent_status(self, agent_id: str, status: str, ticket_id: Optional[str] = None, progress: int = 0) -> None: ...
    def get_all_agents(self) -> List[Dict]: ...
    def get_idle_agents(self) -> List[Dict]: ...
    def get_max_agents(self) -> int: ...
    def set_max_agents(self, max_agents: int) -> None: ...
    def ensure_agent_pool(self) -> None: ...
    def create_agent(self, agent_id: str, name: str, model_name: str = "", skill_names: Optional[List[str]] = None, instruction_ids: Optional[List[int]] = None, repo_affinities: Optional[List[str]] = None) -> Dict: ...
    def update_agent_profile(self, agent_id: str, name: Optional[str] = None, model_name: Optional[str] = None) -> Dict: ...
    def delete_agent(self, agent_id: str) -> None: ...
    def set_agent_skills(self, agent_id: str, skill_names: List[str]) -> None: ...
    def set_agent_instruction_assignments(self, agent_id: str, instruction_ids: List[int]) -> None: ...
    def get_agent_with_profile(self, agent_id: str) -> Optional[Dict]: ...
    def get_all_agents_with_profiles(self) -> List[Dict]: ...
    def get_agent_mcp_servers(self, agent_id: str) -> List[Dict]: ...
    def get_agent_assigned_instructions(self, agent_id: str) -> List[Dict]: ...

    # ── Queue ──────────────────────────────────────────
    def get_next_queue_item(self) -> Optional[Dict]: ...
    def assign_queue_item(self, queue_id: int, agent_id: str) -> bool: ...
    def complete_queue_item(self, queue_id: int) -> None: ...
    def fail_queue_item(self, queue_id: int, error: str) -> None: ...
    def get_queue(self) -> List[Dict]: ...

    # ── Steps ──────────────────────────────────────────
    def add_step(self, queue_id: int, ticket_id: str, agent_id: str, step_name: str, status: str = "running", detail: str = "") -> None: ...
    def get_steps(self, ticket_id: Optional[str] = None, agent_id: Optional[str] = None, queue_id: Optional[int] = None) -> List[Dict]: ...
    def get_all_steps(self) -> List[Dict]: ...

    # ── Settings ───────────────────────────────────────
    def get_all_settings(self) -> List[Dict]: ...
    def get_setting(self, key: str) -> Optional[str]: ...
    def set_setting(self, key: str, value: str) -> None: ...

    # ── Repos ─────────────────────────────────────────
    def get_all_repos(self, active_only: bool = False) -> List[Dict]: ...
    def get_repo(self, name: str) -> Optional[Dict]: ...
    def add_repo(self, name: str, url: str, branch: str = "", description: str = "", tags: Optional[list] = None, active: int = 0) -> bool: ...
    def delete_repo(self, name: str) -> bool: ...
    def update_repo(self, name: str, **fields) -> bool: ...
    def import_repos_from_config(self, config_path: str) -> None: ...
    def set_repo_active(self, name: str, active: bool) -> bool: ...
    def get_agent_repo_affinities(self, agent_id: str) -> List[str]: ...
    def set_agent_repo_affinities(self, agent_id: str, repo_names: List[str]) -> None: ...
    def get_all_repo_names(self) -> List[str]: ...
    def find_best_agent_for_repo(self, primary_repo: str, idle_agents: List[Dict]) -> Optional[str]: ...

    # ── MCP Servers ───────────────────────────────────
    def get_mcp_servers(self) -> List[Dict]: ...
    def get_enabled_mcp_servers(self) -> List[Dict]: ...
    def add_mcp_server(self, data: Dict) -> str: ...
    def update_mcp_server(self, name: str, data: Dict) -> None: ...
    def delete_mcp_server(self, name: str) -> None: ...

    # ── Instructions ──────────────────────────────────
    def get_agent_instructions(self) -> List[Dict]: ...
    def get_enabled_agent_instructions(self) -> str: ...
    def add_agent_instruction(self, data: Dict) -> int: ...
    def update_agent_instruction(self, id: int, data: Dict) -> None: ...
    def delete_agent_instruction(self, id: int) -> None: ...

    # ── Plugins ────────────────────────────────────────
    def get_opencode_plugins(self) -> List[Dict]: ...
    def get_enabled_opencode_plugins(self) -> List[Dict]: ...
    def get_enabled_plugin_names(self) -> List[str]: ...
    def add_opencode_plugin(self, data: Dict) -> str: ...
    def update_opencode_plugin(self, name: str, data: Dict) -> None: ...
    def delete_opencode_plugin(self, name: str) -> None: ...

    # ── Memory ────────────────────────────────────────
    def get_agent_memory_blocks(self, agent_id: str, repo_name: Optional[str] = None) -> List[Dict]: ...
    def set_agent_memory_block(self, agent_id: str, repo_name: str, label: str, content: str, description: str = "", block_limit: int = 5000, read_only: bool = False) -> int: ...
    def get_agent_memory_as_markdown(self, agent_id: str, repo_name: str) -> str: ...
    def delete_agent_memory_block(self, block_id: int) -> None: ...
    def seed_default_memory_blocks(self, agent_id: str) -> None: ...

    # ── Comments ──────────────────────────────────────
    def add_ticket_comment(self, ticket_id: str, author: str = "system", comment_type: str = "comment", content: str = "") -> int: ...
    def get_ticket_comments(self, ticket_id: str) -> List[Dict]: ...

    # ── Groups ────────────────────────────────────────
    def create_ticket_group(self, group_id: str, parent_ticket_id: str, title: str = "", description: str = "") -> str: ...
    def get_ticket_group(self, group_id: str) -> Optional[Dict]: ...
    def add_team_message(self, group_id: str, sender_agent_id: str, content: str, message_type: str = "info") -> int: ...
    def get_team_messages(self, group_id: str, limit: int = 50) -> List[Dict]: ...

    # ── Metrics ───────────────────────────────────────
    def record_metric_event(self, event_type: str, ticket_id: Optional[str] = None, agent_id: Optional[str] = None, phase: Optional[str] = None, duration_seconds: Optional[float] = None, labels: Optional[dict] = None, value: Optional[float] = None) -> None: ...
    def get_metric_events(self, event_type: Optional[str] = None, ticket_id: Optional[str] = None, agent_id: Optional[str] = None, phase: Optional[str] = None, since: Optional[str] = None, limit: int = 1000) -> List[Dict]: ...
    def get_metrics_summary(self, since: Optional[str] = None) -> Dict: ...
    def update_ticket_phase_timestamp(self, ticket_id: str, phase: str) -> None: ...
    def update_ticket_llm_usage(self, ticket_id: str, prompt_tokens: int = 0, completion_tokens: int = 0, cost_usd: float = 0.0, model: str = "") -> None: ...
    def increment_review_cycle_count(self, ticket_id: str) -> None: ...
    def set_ticket_first_pipeline_status(self, ticket_id: str, status: str) -> None: ...
    def set_ticket_completed_at(self, ticket_id: str, status: Optional[str] = None) -> None: ...
    def set_ticket_primary_repo(self, ticket_id: str, primary_repo: str) -> None: ...
    def set_ticket_line_stats(self, ticket_id: str, lines_added: int = 0, lines_removed: int = 0, files_changed: int = 0) -> None: ...