apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-repos
  namespace: hivemind
  labels:
    app.kubernetes.io/name: hivemind
    app.kubernetes.io/component: agent
data:
  repos.json: |
    {
    }
