apiVersion: v1
kind: Secret
metadata:
  name: gitlab-agent-credentials
  namespace: hivemind
  labels:
    app.kubernetes.io/name: hivemind
    app.kubernetes.io/component: agent
type: Opaque
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    PLACEHOLDER: base64 -d <(echo "$GITLAB_SSH_KEY_BASE64") > /tmp/key
    -----END OPENSSH PRIVATE KEY-----
  GITLAB_TOKEN: "glpat-placeholder-token"
