apiVersion: v1
kind: ConfigMap
metadata:
  name: capturecore-ca
  namespace: hivemind
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFWTCCA0GgAwIBAgIUcUGjCnffNk2p3yhxp1c75lVvvEcwDQYJKoZIhvcNAQEL
    BQAwPDELMAkGA1UEBhMCREUxFDASBgNVBAoMC0NhcHR1cmVDb3JlMRcwFQYDVQQD
    DA5DYXB0dXJlQ29yZSBDQTAeFw0yNjA3MjIxMDU5NDVaFw0zNjA3MTkxMDU5NDVa
    MDwxCzAJBgNVBAYTAkRFMRQwEgYDVQQKDAtDYXB0dXJlQ29yZTEXMBUGA1UEAwwO
    Q2FwdHVyZUNvcmUgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/
    KYtevRKrsRsv3BhZ9C8tmxbzU4EKxgCrD+b800IFhY/wZgziQQL+B4T7IAR5BM0H
    tjD0jDdCjukCv7Y49+ZPvxBKBF1FAbcjvRgFn3YNJgT6+ELI8VQlacyjHFNjfsPh
    P4b+o7KZ15ERakcDXfUYybmG9+2pykldOQEXzgycp7dpKtCICVwWywV+WEQRAnVh
    lbrJo+UZeq34HVcdj+EEPkePamMN/G3jra5HvAfnnDQs9y31MH37o2+23TtIfchj
    RZDQ1xZmdm1x6iGc+fyc3FtotMsbbcO2ySxFKGwqvblJT7+5U44fg8vcms1soHfQ
    tEVUrCeyKnnr76wvqYEg43/4SzinNac3TaDL+cKvjScB4lZ1/NXkuypg9m3PtbIm
    tD1zYctd1CKafQ8E2uyXGLjNrxYekOPZieoY+5Vo+rk1QGA1/cOZwlrG5xEBVGPR
    OKUjPAkVvttNBfkcTpZFrTL5yPYMPq1nS/m/OLtBak1FR0YST1B4m3uqQVyr3VWa
    NVPgAk7FCDD5Auu6CcnRiEXRvpm3Ml7QSzv7x7kIaKsFNqpIYg2Xrmltf5zTP9Cg
    MHOyvdxeRXtVmxzBzWFAB+b3bpTzbwGDHp519p00pEaK4qXD57F/KUktx86oj2VV
    LgUSpCEELT+CYsVpVZ7VZwm3bMLgqYOp/6aePNp5kQIDAQABo1MwUTAdBgNVHQ4E
    FgQUkDR0orM4vhxDA15kGKEJu1IHsHUwHwYDVR0jBBgwFoAUkDR0orM4vhxDA15k
    GKEJu1IHsHUwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAmzkv
    XuP6zydtpA/vskiQfq52MULnaos9CncKka0A++9/Q1eyXqLKIQ5cYZuKgGPtPP4s
    s0BYN3FPytHXK64Q4qJTqvo2ONekrLGZxIDcl8c/DqPXGopGmZHuLmQL+7WKlKfy
    f74Vt/dTtH1hF16Xfu3giL3WT6FZmyTmtaS0D+0amDJsoXt+LdQXVuZMIUx82Zal
    yAj7AAMWYen6IU1dobTrRqj0TtAA9inxNow0Knkoy8gofD/aGylOsySKFNeTHdQY
    4NzgooJuzCgWDP0Oh7dv8NbNngSH6Z0gleI71oQGs3jGdnTJuB0aYDTp9aaVISe7
    4eUwESqFP0kKsuB8Sn2h/EnOKzEpwMTlpI78dW+AqxXOAZgZn6PMlIjgqkTXMCJP
    maNic1JUf4lAXor0lpnxqsSblsx8r2L0Esmvdig1fnCiBE47DCvrGRk3ktl7L1T+
    WUJ+7KVBIQH/HZeTliGZUsngYrc87npBLKVpZjnnu8fbQxyv92fbexd5seDMik/Y
    Rp2vCP/Oven79PI6UTi8v8n5Bf2pq92xp1L/nU1m2BNVJ/w+sajZKMB3yRZxMEsW
    TU4ofOHOYzmcGRWvbz2aasGjQTbKP7H84jBGvbeklCVAuxme4Is7/27vGgnSdzqd
    loruuUMCId7THCw2TdWRrt9Dslw06cvYE9bXaT8=
    -----END CERTIFICATE-----