apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-db-pvc
  namespace: hivemind
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi