apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-db-pvc
  namespace: hivemind
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi