apiVersion: v1
kind: ResourceQuota
metadata:
  name: hivemind-quota
  namespace: hivemind
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 64Gi
    limits.cpu: "32"
    limits.memory: 128Gi
    pods: "30"
    persistentvolumeclaims: "20"
    configmaps: "200"
    secrets: "50"