apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivemind

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: orchestrator
  app.kubernetes.io/component: orchestrator

images:
  - name: hivemind-orchestrator
    newName: hivemind-orchestrator
    newTag: 0.1.38
