apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivemind

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - capturecore-ca.yaml

commonLabels:
  app.kubernetes.io/name: hivemind
  app.kubernetes.io/component: orchestrator

images:
  - name: hivemind-orchestrator
    newName: reg.capturecore.org/capturecore/hivemind-orchestrator
    newTag: latest
