apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-repos
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-db
spec:
  storageClassName: longhorn-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
